### ISSUE TITLE
[1.12] Crash with Forge 2389

### ISSUE THREAD

**Issue by MokahTGS** [crazysnailboy/VanillaTeleporter#4]
Getting a crash with Forge v2389 and Beta 2 for 1.12.

https://pastebin.com/eAytanYG

**Comment by crazysnailboy** [comment]
Hi - thanks for pointing this out :) I've uploaded [v1.6.3-beta3](https://minecraft.curseforge.com/projects/vanilla-teleporters/files/2445311/download) to fix it.
