### ISSUE TITLE
1.12: Getting Fatally Missing Mods when joining my server.

### ISSUE THREAD

**Issue by dragon3025** [crazysnailboy/VanillaTeleporter#6]
I tested this out, by having only this mod in both the server and the client folder. I join and it gives me a "Fatally Missing Mods" error. I'm using forge-1.12-14.21.1.2387.

**Comment by crazysnailboy** [comment]
Thanks for pointing this out. I've uploaded [v1.6.3-beta4](https://minecraft.curseforge.com/projects/vanilla-teleporters/files/2449620/download) to fix it.
